# Flujo completo - Regresión Lineal

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import cross_val_score
import numpy as np

# Importamos datos en un Dataframe

In [8]:
df_data = pd.read_excel(r'./data/Precio_coches.xlsx')

In [9]:
df_data.head() # Variable output --> "Precio"

,Fabricante,Combustible,Longitud,Ancho,Altura,Numero_cilindros,Potencia,RPM_pico,Precio
0,alfa-romero,gas,168.8,64.1,48.8,4,111,5000,13495
1,alfa-romero,gas,168.8,64.1,48.8,4,111,5000,16500
2,alfa-romero,gas,171.2,65.5,52.4,6,154,5000,16500
3,audi,gas,176.6,66.2,54.3,4,102,5500,13950
4,audi,gas,176.6,66.4,54.3,5,115,5500,17450

# Convertir Variables categóricas de entrada (X)

In [10]:
df_X = df_data.drop('Precio', axis=1)

In [11]:
df_X = pd.get_dummies(df_X)

In [12]:
df_X.head()

,Longitud,Ancho,Altura,Numero_cilindros,Potencia,RPM_pico,Fabricante_alfa-romero,Fabricante_audi,Fabricante_bmw,Fabricante_chevrolet,...,Fabricante_peugot,Fabricante_plymouth,Fabricante_porsche,Fabricante_saab,Fabricante_subaru,Fabricante_toyota,Fabricante_volkswagen,Fabricante_volvo,Combustible_diesel,Combustible_gas
0,168.8,64.1,48.8,4,111,5000,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,168.8,64.1,48.8,4,111,5000,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,171.2,65.5,52.4,6,154,5000,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,176.6,66.2,54.3,4,102,5500,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
4,176.6,66.4,54.3,5,115,5500,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True

# Crear un array (dataframe) con las variables de entrada (X) y otro para la variable de salida (y)

In [13]:
X = df_X.values
y = df_data['Precio'].values

# Dividir datos en conjunto de "Training" (ej: 80%) y conjunto de "Test" (ej:20%)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

# Construir Modelos Regresión Lineal

In [15]:
reg = LinearRegression()

# Entrenamos el modelo

In [16]:
reg.fit(X_train, y_train)

LinearRegression()

# Cross-validación - Verificación Precisión

In [17]:
# Compute 5-fold cross-validation scores: cv_scores
cv_scores = cross_val_score(reg,X_train,y_train,cv=5)

# Print the 5-fold cross-validation scores
print(cv_scores)

print("Average 5-Fold CV Score: {}".format(np.mean(cv_scores)))

[0.56837164 0.80633888 0.76104556 0.77054998 0.89253416]
Average 5-Fold CV Score: 0.7597680414560766

# Predicción con los datos de TEST

In [18]:
y_pred = reg.predict(X_test)

In [19]:
y_pred

array([ 8455.21210829, 28630.37997408, 16433.48500684,  9909.68905579,
        8054.62262109, 12202.2742713 , 36799.00109902, 34545.50079503,
        7988.36991721, 17695.88188717,  9038.62326486,  6276.39038644,
       33125.37686536,  6795.02214898,  6592.00077292, 10543.85843645,
       13578.13104089, 11137.30140083,  7027.39857856, 10493.95289743,
       29405.65523415, 31963.53114337,  9703.78453978, 17695.88188717,
       33267.84808149, 16924.23363216,  6276.39038644, 19144.99894174,
        7853.44528229, 14178.57230915, 17052.84398401, 29197.84284325,
       20882.01417881, 12202.2742713 , 16665.64653655, 35506.53588244,
       14178.57230915, 31963.53114337,  5550.5058176 ,  8714.06040817])

# Computar el error cuadrático medio RMSE

In [20]:
print("R^2: {}".format(reg.score(X_test, y_test)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error: {}".format(rmse))

R^2: 0.9125460025421429
Root Mean Squared Error: 3144.4819091407094