# Flujo completo - Regresión Lineal

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import cross_val_score
import numpy as np

# Importamos datos en un Dataframe

Carga los datos del archivo Excel "Precio_coches.xlsx" en un DataFrame de pandas. Asegúrate de que el archivo esté ubicado en la ruta correcta y que el nombre del archivo sea correcto. El DataFrame resultante se almacenará en la variable `df_data`.

In [4]:
df = pd.read_excel('data/Precio_coches.xlsx')

Haz un head() del DataFrame para verificar que los datos se hayan cargado correctamente y para obtener una vista previa de las primeras filas del conjunto de datos. Esto te permitirá confirmar que la columna "Precio" está presente y que las demás columnas también se han importado correctamente.

In [5]:
df.head()

,Fabricante,Combustible,Longitud,Ancho,Altura,Numero_cilindros,Potencia,RPM_pico,Precio
0,alfa-romero,gas,168.8,64.1,48.8,4,111,5000,13495
1,alfa-romero,gas,168.8,64.1,48.8,4,111,5000,16500
2,alfa-romero,gas,171.2,65.5,52.4,6,154,5000,16500
3,audi,gas,176.6,66.2,54.3,4,102,5500,13950
4,audi,gas,176.6,66.4,54.3,5,115,5500,17450

# Convertir Variables categóricas de entrada (X)

Eliminar la columna "Precio" del DataFrame para crear un nuevo DataFrame `df_X` que contenga solo las variables de entrada (X). Esto se hace utilizando el método `drop()` de pandas, especificando el nombre de la columna a eliminar y el eje (axis=1) para indicar que se trata de una columna.

In [9]:
X = df.drop('Precio', axis=1)

Convertir las variables categóricas en el DataFrame `df_X` a variables dummy utilizando la función `get_dummies()` de pandas. Esto creará nuevas columnas para cada categoría de las variables categóricas, con valores binarios (0 o 1) que indican la presencia o ausencia de cada categoría. El resultado se almacenará nuevamente en `df_X`.

In [13]:
df_X = pd.get_dummies (X, drop_first=True)  # Parentesis evita datos iguales/semejantes (multicolinealidad) ---

Haz un head() del DataFrame `df_X` para verificar que las variables categóricas se hayan convertido correctamente en variables dummy. Esto te permitirá confirmar que las nuevas columnas se han creado y que los datos están listos para ser utilizados como variables de entrada (X) en el modelo de regresión.

In [14]:
df_X.head()

,Longitud,Ancho,Altura,Numero_cilindros,Potencia,RPM_pico,Fabricante_audi,Fabricante_bmw,Fabricante_chevrolet,Fabricante_dodge,...,Fabricante_nissan,Fabricante_peugot,Fabricante_plymouth,Fabricante_porsche,Fabricante_saab,Fabricante_subaru,Fabricante_toyota,Fabricante_volkswagen,Fabricante_volvo,Combustible_gas
0,168.8,64.1,48.8,4,111,5000,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,168.8,64.1,48.8,4,111,5000,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,171.2,65.5,52.4,6,154,5000,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,176.6,66.2,54.3,4,102,5500,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,176.6,66.4,54.3,5,115,5500,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

# Crear un array (dataframe) con las variables de entrada (X) y otro para la variable de salida (y)

Crear un array `X` que contenga los valores de las variables de entrada (X) utilizando el atributo `values` del DataFrame `df_X`. Esto convertirá el DataFrame en un array de NumPy. De manera similar, crear un array `y` que contenga los valores de la variable de salida (y) utilizando el mismo método en la columna "Precio" del DataFrame `df_data`.

In [17]:
#Esa conversión es buena para la velocidad, memoria(menos espacio) y compatibilidad de los datos

x =df_X.values
y = df['Precio'].values

# Dividir datos en conjunto de "Training" (ej: 80%) y conjunto de "Test" (ej:20%)

Dividir los datos en conjuntos de entrenamiento y prueba utilizando la función `train_test_split()` de scikit-learn. Especifica el array `X` como las variables de entrada, el array `y` como la variable de salida, el tamaño del conjunto de prueba (test_size) como 0.2 para reservar el 20% de los datos para pruebas, y un valor de random_state (por ejemplo, 42) para garantizar la reproducibilidad de la división. El resultado se almacenará en las variables `X_train`, `X_test`, `y_train` y `y_test`.

# Construir Modelos Regresión Lineal

Construir un modelo de regresión lineal utilizando la clase `LinearRegression` de scikit-learn. Crea una instancia del modelo y almacénala en la variable `reg`.

# Entrenamos el modelo

Entrenar el modelo de regresión lineal utilizando el método `fit()` del modelo `reg`, pasando los conjuntos de entrenamiento `X_train` y `y_train` como argumentos. Esto ajustará el modelo a los datos de entrenamiento.

LinearRegression()

# Cross-validación - Verificación Precisión

Realizar una validación cruzada de 5 pliegues utilizando la función `cross_val_score()` de scikit-learn. Pasa el modelo `reg`, los datos de entrenamiento `X_train` y `y_train`, y el número de pliegues (cv=5) como argumentos. Esto calculará las puntuaciones de validación cruzada para cada pliegue y las almacenará en la variable `cv_scores`.

[0.56837164 0.80633888 0.76104556 0.77054998 0.89253416]
Average 5-Fold CV Score: 0.7597680414560766

# Predicción con los datos de TEST

Realizar predicciones utilizando el modelo entrenado `reg` en el conjunto de prueba `X_test` utilizando el método `predict()`. Almacena las predicciones en la variable `y_pred`.

Comparar las predicciones `y_pred` con los valores reales `y_test` para evaluar el rendimiento del modelo. Esto te permitirá ver cómo se desempeña el modelo en datos que no se utilizaron durante el entrenamiento.

array([ 8455.21210829, 28630.37997408, 16433.48500684,  9909.68905579,
        8054.62262109, 12202.2742713 , 36799.00109902, 34545.50079503,
        7988.36991721, 17695.88188717,  9038.62326486,  6276.39038644,
       33125.37686536,  6795.02214898,  6592.00077292, 10543.85843645,
       13578.13104089, 11137.30140083,  7027.39857856, 10493.95289743,
       29405.65523415, 31963.53114337,  9703.78453978, 17695.88188717,
       33267.84808149, 16924.23363216,  6276.39038644, 19144.99894174,
        7853.44528229, 14178.57230915, 17052.84398401, 29197.84284325,
       20882.01417881, 12202.2742713 , 16665.64653655, 35506.53588244,
       14178.57230915, 31963.53114337,  5550.5058176 ,  8714.06040817])

# Computar el error cuadrático medio RMSE

Calcular el coeficiente de determinación (R^2) utilizando el método `score()` del modelo `reg`, pasando el conjunto de prueba `X_test` y `y_test` como argumentos. Esto te dará una medida de qué tan bien el modelo se ajusta a los datos de prueba. Luego, calcular la raíz del error cuadrático medio (RMSE) utilizando la función `mean_squared_error()` de scikit-learn, pasando los valores reales `y_test` y las predicciones `y_pred` como argumentos, y tomando la raíz cuadrada del resultado. Imprimir ambos resultados para evaluar el rendimiento del modelo.

R^2: 0.9125460025421429
Root Mean Squared Error: 3144.4819091407094